server:
  port: 19090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  config:
    profile: local
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.204.17.52:48349;encrypt=true;trustServerCertificate=true
    username: ifuser
    password: WElcome12!@
#    driver-class-name: org.h2.Driver  
#    url: jdbc:h2:tcp://localhost/~/test
#    username: choi
#    password: 1234
  batch:
    job:
      enabled: false
  mybatis:
    mapper-locations: classpath:mapper/DataBaseMapper.xml
    config-location: classpath:config/mybatis-config.xml

logging:
    config: classpath:config/logback-local.xml         