package com.deloitte.solution.entity;

public class Test {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEST.ID
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEST.USERID
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEST.COMPANYNAME
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	private String companyname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TEST.AGE
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	private String age;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEST.ID
	 * @return  the value of TEST.ID
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEST.ID
	 * @param id  the value for TEST.ID
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEST.USERID
	 * @return  the value of TEST.USERID
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEST.USERID
	 * @param userid  the value for TEST.USERID
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEST.COMPANYNAME
	 * @return  the value of TEST.COMPANYNAME
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	public String getCompanyname() {
		return companyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEST.COMPANYNAME
	 * @param companyname  the value for TEST.COMPANYNAME
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	public void setCompanyname(String companyname) {
		this.companyname = companyname == null ? null : companyname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TEST.AGE
	 * @return  the value of TEST.AGE
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	public String getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TEST.AGE
	 * @param age  the value for TEST.AGE
	 * @mbg.generated  Tue Sep 20 16:59:28 KST 2022
	 */
	public void setAge(String age) {
		this.age = age == null ? null : age.trim();
	}
}