package com.deloitte.solution.base.mapper;

import com.deloitte.solution.entity.Test;
import java.util.List;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Fri Sep 16 16:48:13 KST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Fri Sep 16 16:48:13 KST 2022
     */
    int insert(Test row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Fri Sep 16 16:48:13 KST 2022
     */
    Test selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Fri Sep 16 16:48:13 KST 2022
     */
    List<Test> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST
     *
     * @mbg.generated Fri Sep 16 16:48:13 KST 2022
     */
    int updateByPrimaryKey(Test row);
}